language: ruby
rvm:
  - 2.1.1
script:
  - sudo pip install html5validator
  - bundle exec jekyll build
  - bundle exec htmlproof ./_site
  - html5validator --root ./_site
branches:
  only:
    - gh-pages
