sudo: required

language: ruby
rvm:
  - 2.1.1

install:
  - export PATH=$HOME/.local/bin:$PATH
  - pip install --user html5validator

script:
  - bundle exec jekyll build
  - bundle exec htmlproof ./_site
  - html5validator --root ./_site

branches:
  only:
    - gh-pages
